# Introduction to numpy

### Package for scientific computing with Python

* Numerical Python, or "Numpy" for short
* foundational package on which many of the most common data science packages are built.
* high performance multi-dimensional arrays.  
* key benefits: **speed** and **functionality**.

## Numpy

The key features of numpy are:

- **ndarrays**: n-dimensional arrays of the same data type which are fast and space-efficient.
- **Broadcasting**: a useful tool which defines implicit behavior between multi-dimensional arrays of different sizes.
- **Vectorization**: enables numeric operations on ndarrays.
- **Input/Output**: simplifies reading and writing of data from/to file.

### Benefits and characteristics of NumPy arrays


NumPy arrays have several advantages over Python lists. 

1. High-performance manipulation of sequences of homogenous data items

2. Vectorized operations

3. Boolean selection

4. Sliceability

### Difference between Numpy and Python

### standard deviation

In [1]:
a = [1,2,3,4,5,6,7,8,9]

In [2]:
import numpy as np

### standard deviation (python)

In [3]:
import math

def std(lst):
    mean = sum(lst) / len(lst)
    variance = 0
    for e in lst:
        variance += (e - mean) ** 2
    variance /= len(lst)
    
    return math.sqrt(variance)

std(a)

2.449489742783178

### standard deviation (numpy)

In [4]:
a = np.array(a)
a.std()

2.5819888974716112

### covariance matrix (numpy)

In [5]:
x = np.array([1,2,3,4,5,6,7,8,9])
y = np.array([9,8,7,6,5,4,3,2,1])

np.cov(x, y)

array([[ 7.5, -7.5],
       [-7.5,  7.5]])

### Getting started with ndarray

**ndarrays** are time and space-efficient multidimensional arrays at the core of numpy.

### How to create 1 dimensional numpy arrays

In [6]:
import numpy as np                 # Importing numpy

In [7]:
an_array = np.array([3, 33, 333])  # Create a 1 dimensional array

In [8]:
print(type(an_array))              # The type of an ndarray is: "<class 'numpy.ndarray'>"

<type 'numpy.ndarray'>


In [9]:
# test the shape of the array we just created, it should have just one dimension
print(an_array.shape)

(3,)


### Indexing

In [10]:
# because this is a 1-rank array, we need only one index to accesss each element
print(an_array[0], an_array[1], an_array[2]) 

(3, 33, 333)


In [11]:
an_array[0] = 888                 # ndarrays are mutable, here we change an element of the array

print(an_array)

[888  33 333]


### How to create a 2 dimensional numpy array

Notice the format below of [ [row] , [row] ].  2 dimensional arrays are great for representing matrices which are often useful in data science.

In [12]:
another = np.array([[11,12,13],[21,22,23]])   # Create a 2 dimensional array

In [13]:
print(another)  # print the array

[[11 12 13]
 [21 22 23]]


In [14]:
print("The shape is 2 rows, 3 columns: ", another.shape)  # rows x columns                   

('The shape is 2 rows, 3 columns: ', (2, 3))


In [15]:
print("Accessing elements [0,0], [0,1], and [1,0] of the ndarray: ", 
      another[0, 0], ", ",another[0, 1],", ", another[1, 0])

('Accessing elements [0,0], [0,1], and [1,0] of the ndarray: ', 11, ', ', 12, ', ', 21)


### Ways to create numpy arrays

In [16]:
# create a 2x2 array of zeros
ex1 = np.zeros((2,2))      
print(ex1)                              

[[ 0.  0.]
 [ 0.  0.]]


In [17]:
# create a 2x2 array filled with 9.0
ex2 = np.full((2,2), 9.0)  
print(ex2)   

[[ 9.  9.]
 [ 9.  9.]]


### Ways to create numpy arrays

In [18]:
# create a 2x2 matrix with the diagonal 1s and the others 0
ex3 = np.eye(2,2)
print(ex3)  

[[ 1.  0.]
 [ 0.  1.]]


In [19]:
# create an array of ones
ex4 = np.ones((1,2))
print(ex4)    

[[ 1.  1.]]


In [20]:
# notice that the above ndarray (ex4) is actually rank 2, it is a 2x1 array
print(ex4.shape)

(1, 2)


In [21]:
# which means we need to use two indexes to access an element
print(ex4[0,1])

1.0


### Ways to create numpy arrays

In [22]:
# create an array of random floats between 0 and 1
ex5 = np.random.random((2,2))
print(ex5)    

[[ 0.16641614  0.23545732]
 [ 0.05304491  0.62688956]]


### Array Indexing

#### Slice indexing:

- use slice indexing to pull out sub-regions of ndarrays.

In [23]:
# Rank 2 array of shape (3, 4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])

In [24]:
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


#### Slice indexing
Use array slicing to get a subarray consisting of the first 2 rows x 2 columns.

In [25]:
a_slice = an_array[:2, 1:3]
print(a_slice)

[[12 13]
 [22 23]]


#### Slice indexing
When you modify a slice, you actually modify the underlying array.

In [26]:
print("Before:", an_array[0, 1])   #inspect the element at 0, 1  
a_slice[0, 0] = 1000    # a_slice[0, 0] is the same piece of data as an_array[0, 1]
print("After:", an_array[0, 1])    

('Before:', 12)
('After:', 1000)


#### Integer & Slice indexing

We can use combinations of integer indexing and slice indexing to create different shaped matrices.

In [27]:
# Create a Rank 2 array of shape (3, 4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])

In [28]:
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


#### Integer & Slice indexing

In [29]:
# Using both integer indexing & slicing generates an array of lower rank
row_rank1 = an_array[1, :]    # Rank 1 view 

print(row_rank1, row_rank1.shape)  # notice only a single []

(array([21, 22, 23, 24]), (4,))


In [30]:
# Slicing alone: generates an array of the same rank as the an_array
row_rank2 = an_array[1:2, :]  # Rank 2 view 

print(row_rank2, row_rank2.shape)   # Notice the [[ ]]

(array([[21, 22, 23, 24]]), (1, 4))


In [31]:
#We can do the same thing for columns of an array:
col_rank1 = an_array[:, 1]
col_rank2 = an_array[:, 1:2]

print(col_rank1, col_rank1.shape)  # Rank 1
print()
print(col_rank2, col_rank2.shape)  # Rank 2

(array([12, 22, 32]), (3,))
()
(array([[12],
       [22],
       [32]]), (3, 1))


### Array Indexing for changing elements

In [32]:
# Create a new array
an_array = np.array([[11,12,13], [21,22,23], [31,32,33], [41,42,43]])

In [33]:
print('Original Array:')
print(an_array)

Original Array:
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


### Array Indexing for changing elements

In [34]:
# Create an array of indices
col_indices = np.array([0, 1, 2, 0])
print('\nCol indices picked : ', col_indices)

('\nCol indices picked : ', array([0, 1, 2, 0]))


In [35]:
row_indices = np.arange(4)
print('\nRows indices picked : ', row_indices)

('\nRows indices picked : ', array([0, 1, 2, 3]))


In [36]:
# Examine the pairings of row_indices and col_indices.  These are the elements we'll change next.
for row,col in zip(row_indices,col_indices):
    print(row, ", ",col)

(0, ', ', 0)
(1, ', ', 1)
(2, ', ', 2)
(3, ', ', 0)


### Array Indexing for changing elements

In [37]:
# Select one element from each row
print('Values in the array at those indices: ',an_array[row_indices, col_indices])

('Values in the array at those indices: ', array([11, 22, 33, 41]))


In [38]:
# Change one element from each row using the indices selected
an_array[row_indices, col_indices] += 100000

In [39]:
print('\nChanged Array:')
print(an_array)


Changed Array:
[[100011     12     13]
 [    21 100022     23]
 [    31     32 100033]
 [100041     42     43]]


### Hands-on Exercise 1: Get portion of numpy array

In [43]:
# DO NOT MODIFY

# we will use this dummy matrix for some portions of this exercise.

def get_matrix():
    return np.array(
      [[ 0.35066314,  0.94844269,  0.69324339,  -0.32790416],
       [ -0.7935923 ,  0.9212632 ,  0.13607887,  0.56358399],
       [ 0.25597054,  0.74834666,  -0.81322464,  0.11280075],
       [ -0.53822742,  -0.63970183,  0.1439784 ,  0.58045905]])

mat = get_matrix()

In the cell below, modify the function to RETURN elements occuring in first two rows and 2nd-3rd columns

In [44]:
# modify this cell

def find_slice(matx):
    ### BEGIN SOLUTION

    ### END SOLUTION

In [45]:
# DO NOT MODIFY
ans = [[ 0.94844269,  0.69324339],[ 0.9212632 ,  0.13607887]]

try: assert np.alltrue(find_slice(mat) == np.array(ans))
except AssertionError as e: print("Try again, your output did not match the expected answer above")

In [53]:
l = np.array([1,2,3,4])
l2 = l[:]

l2[0] = 23
print l
print l2

[23  2  3  4]
[23  2  3  4]


### Hands-on Exercise 2: Update portion of numpy array

In the cell below, modify the function to perform in-place addition of 1000 to every element of slice you just created and RETURN the changed version

In [ ]:
# modify this cell

def update_slice(matx):
    ### BEGIN SOLUTION

    return matx
    ### END SOLUTION

In [ ]:
# DO NOT MODIFY

ans = [[ 1000.94844269,  1000.69324339],[ 1000.9212632 ,  1000.13607887]]

try: 
    mat=get_matrix()
    update_slice(mat)
    assert np.alltrue(find_slice(mat) == np.array(ans))
except AssertionError as e: print("Try again: be sure to check both your update_slice and find_slide functions.")

### Boolean Indexing

In [ ]:
# create a 3x2 array
an_array = np.array([[11,12], [21, 22], [31, 32]])
print(an_array)

In [ ]:
# create a filter which will be boolean values for whether each element meets this condition
filter = (an_array > 15)
print (filter)

### Boolean Indexing

In [ ]:
# we can now select just those elements which meet that criteria
print(an_array[filter])

In [ ]:
# For short, we could have just used the approach below without the need for the separate filter array.
print( an_array[an_array > 15] )

### Boolean Indexing

What is particularly useful is that we can actually change elements in the array applying a similar logical filter.  Let's add 100 to all the even values.

In [ ]:
an_array[an_array % 2 == 0] +=100
print(an_array)

### Hands-on Exercise 3: Filter numpy array

In the cell below, modify the function to RETURN elements of matrix that are greater than 1

In [ ]:
# modify this cell

def bool_filter(matx):
    ### BEGIN SOLUTION

    ### END SOLUTION

In [ ]:
# DO NOT MODIFY

ans = [1000.94844269,  1000.69324339,  1000.9212632, 1000.13607887]


try: assert np.alltrue(bool_filter(mat) == np.array(ans))
except AssertionError as e: print("Try again, your solution did not produce the expected output above")

### Datatypes and Array Operations

### Datatypes

In [ ]:
ex1 = np.array([11, 12]) # Python assigns the  data type
print(ex1.dtype)

In [ ]:
ex2 = np.array([11.0, 12.0]) # Python assigns the  data type
print(ex2.dtype)

In [ ]:
ex3 = np.array([11, 21], dtype=np.int64) #You can also tell Python the  data type
print(ex3.dtype)

### Datatypes

In [ ]:
# you can use this to force floats into integers (using floor function)
ex4 = np.array([11.1,12.7], dtype=np.int64)
print(ex4.dtype)

In [ ]:
print(ex4)

In [ ]:
# you can use this to force integers into floats if you anticipate
# the values may change to floats later
ex5 = np.array([11, 21], dtype=np.float64)
print(ex5.dtype)

In [ ]:
print(ex5)

### Hands-on Exercise 4: Int Converter


In the cell below, modify the function to convert each element of entered matrix to np.int data type AND return a new matrix with converted data type (i.e. full of integers)

In [ ]:
# modify this cell

def int_converter(matx):
    ### BEGIN SOLUTION

    ### END SOLUTION

In [ ]:
# DO NOT MODIFY

ans = [[   0, 1000, 1000,    0],
       [   0, 1000, 1000,    0],
       [   0,    0,    0,    0],
       [   0,    0,    0,    0]]

try: assert np.alltrue(int_converter(mat) == np.array(ans))
except AssertionError as e: print("Try again - be sure your code from Exercise 2 worked properly as well.")

### Arithmetic Array Operations

In [ ]:
x = np.array([[111,112],[121,122]], dtype=np.int)
print(x)

In [ ]:
y = np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)
print(y)

### Addition

In [ ]:
print(x + y)         # The plus sign works

In [ ]:
print(np.add(x, y))  # so does the numpy function "add"

### Subtraction

In [ ]:
print(x - y)

In [ ]:
print(np.subtract(x, y))

### Multiplication

In [ ]:
print(x * y)

In [ ]:
print(np.multiply(x, y))

### Division

In [ ]:
print(x / y)

In [ ]:
print(np.divide(x, y))

### Square Root & Exponentiation

In [ ]:
# square root
print(np.sqrt(x))

In [ ]:
# exponent (e ** x)
print(np.exp(x))

### Statistical Methods, Sorting, and Set Operations

### Basic Statistical Operations

In [ ]:
# setup a random 2 x 4 matrix
arr = 10 * np.random.randn(2,5)
print(arr)

### Mean

In [ ]:
# compute the mean for all elements
print(arr.mean())

In [ ]:
# compute the means by row
print(arr.mean(axis = 1))

In [ ]:
# compute the means by column
print(arr.mean(axis = 0))

### Sorting

In [ ]:
# create a 10 element array of randoms
unsorted = np.random.randn(10)
print(unsorted)

In [ ]:
# create copy and sort
sorted = np.array(unsorted)
sorted.sort()
print(sorted)

In [ ]:
# inplace sorting
unsorted.sort() 
print(unsorted)

### Hands-on Exercise 5: More Filtering

In the cell below, modify the function to perform inplace update of input matrix such that
each element that is negative is replaced with 0. <br> Note that the function does not return anything but changes the matrix inplace.

In [ ]:
# modify this cell

def selective_replace(matx):
    ### BEGIN SOLUTION

    ### END SOLUTION

In [ ]:
# DO NOT MODIFY
mat = get_matrix()
ans = np.array([[ 0.35066314,  0.94844269,  0.69324339,  0.        ],
                [ 0.,          0.9212632,   0.13607887,  0.56358399],
                [ 0.25597054,  0.74834666,  0.,          0.11280075],
                [ 0.,          0.,          0.1439784,   0.58045905]])
try: 
    selective_replace(mat)
    assert np.alltrue(mat == ans)
except AssertionError as e: print("Try again, your function did not produce the expected output above.")

### Finding Unique elements

In [ ]:
array = np.array([1,2,1,4,2,1,4,2])

print(np.unique(array))

### Set Operations with np.array data type

In [ ]:
s1 = np.array(['desk','chair','bulb'])
s2 = np.array(['lamp','bulb','chair'])
print(s1, s2)

### Set Operations with np.array data type

In [ ]:
print( np.intersect1d(s1, s2) )    # Intersection

In [ ]:
print( np.union1d(s1, s2) )       # Union

In [ ]:
print( np.setdiff1d(s1, s2) )     # elements in s1 that are not in s2

In [ ]:
print( np.in1d(s1, s2) )          # which element of s1 is also in s2

### Broadcasting

In [ ]:
start = np.zeros((4,3))
print(start)

In [ ]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2])
print(add_rows)

In [ ]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

### Broadcasting

In [ ]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T

print(add_cols)

In [ ]:
y = start + add_cols # add to each column of 'start' using broadcasting
print(y)

### Broadcasting

In [ ]:
add_scalar = np.array([1])  # this will just broadcast in both dimensions
print(start+add_scalar)

### Hands-on Exercise 6: Broadcasting  

add first row to every row of the input matrix

In the cell below, modify the function to RETURN a new matrix by taking first row of the input matrix and adding it to every row of entered matrix.

So if the input matrix is:
2, 3
1, 4

The output should be:
4, 6
3, 7

See how the first row (2,3) was added to itself and all subsequent rows.

In [ ]:
# modify this cell

def first_row_adder(matx):
    ### BEGIN SOLUTION

    ### END SOLUTION
    
# modify this cell

In [ ]:
# DO NOT MODIFY
test = np.array([[ 22.33,  4.53, 10.64],[ 10.64 ,  4.53, 100.97]])
ans = [[  44.66,    9.06,   21.28], [  32.97,    9.06,  111.61]]

try: assert np.allclose(first_row_adder(test), np.array(ans))
except AssertionError as e: print("Try again, first row was not added to all other rows")

### Speed Test: ndarrays vs lists

First setup paramaters for the speed test.  We'll be testing time to sum elements in an ndarray versus a list.

In [ ]:
from timeit import Timer

size    = 1000000
timeits = 1000

### Numpy

In [ ]:
# create the ndarray with values 0,1,2...,size-1
nd_array = np.arange(size)
print( type(nd_array) )

In [ ]:
# timer expects the operation as a parameter, here we pass nd_array.sum()
timer_numpy = Timer("nd_array.sum()", "from __main__ import nd_array")

print("Time taken by numpy ndarray: %.3e" % (timer_numpy.timeit(timeits)/timeits))

### Python

In [ ]:
# create the list with values 0,1,2...,size-1
a_list = list(range(size))
print (type(a_list) )

In [ ]:
# timer expects the operation as a parameter, here we pass sum(a_list)
timer_list = Timer("sum(a_list)", "from __main__ import a_list")

print("Time taken by list:  %.3e" % (timer_list.timeit(timeits)/timeits))

### Read or Write to Disk

#### Binary Format

In [ ]:
x = np.array([ 23.23, 24.24] )

np.save('an_array', x)

np.load('an_array.npy')

#### Text Format

In [ ]:
np.savetxt('array.txt', X=x, delimiter=',')

!cat array.txt

In [ ]:
np.loadtxt('array.txt', delimiter=',')

### Additional Common ndarray Operations

### Dot Product on Matrices

In [ ]:
# determine the dot product of two matrices
x2d = np.array([[1,1],[1,1]])
y2d = np.array([[2,2],[2,2]])

In [ ]:
print(x2d.dot(y2d))

In [ ]:
print(np.dot(x2d, y2d))

###  Inner Product on Vectors

In [ ]:
# determine the inner product of two vectors
a1d = np.array([9 , 9 ])
b1d = np.array([10, 10])

In [ ]:
print(a1d.dot(b1d))

In [ ]:
print(np.dot(a1d, b1d))

### Dot Product on Matrix and vector

In [ ]:
# dot produce on an array and vector
print(x2d.dot(a1d))

In [ ]:
print(np.dot(x2d, a1d))

### Element-wise Functions:

For example, let's compare two arrays values to get the maximum of each.

In [ ]:
# random array
x = np.random.randn(8)
x

In [ ]:
# another random array
y = np.random.randn(8)
y

In [ ]:
# returns element wise maximum between two arrays

np.maximum(x, y)

### Reshaping array:

In [ ]:
# grab values from 0 through 19 in an array
arr = np.arange(20)
print(arr)

In [ ]:
# reshape to be a 4 x 5 matrix
arr.reshape(4,5)

### Transpose:

In [ ]:
# transpose
ex1 = np.array([[11,12],[21,22]])

ex1.T

### Indexing using where():

In [ ]:
x_1 = np.array([1,2,3,4,5])

y_1 = np.array([11,22,33,44,55])

filter = np.array([True, False, True, False, True])

In [ ]:
out = np.where(filter, x_1, y_1)
print(out)

### Indexing using where():

In [ ]:
mat = np.random.rand(5,5)
mat

In [ ]:
np.where( mat > 0.5, 1000, -1)

### "any" or "all" conditionals:

In [ ]:
arr_bools = np.array([ True, False, True, True, False ])

In [ ]:
arr_bools.any()

In [ ]:
arr_bools.all()

### Random Number Generation:

In [ ]:
Y = np.random.normal(size = (1,5))[0]
print(Y)

In [ ]:
Z = np.random.randint(low=2,high=50,size=4)
print(Z)

In [ ]:
np.random.permutation(Z) #return a new ordering of elements in Z

### Random Number Generation:

In [ ]:
np.random.uniform(size=4) #uniform distribution

In [ ]:
np.random.normal(size=4) #normal distribution

### Merging data sets

In [ ]:
K = np.random.randint(low=2,high=50,size=(2,2))
print(K)

In [ ]:
M = np.random.randint(low=2,high=50,size=(2,2))
print(M)

### Merging data sets along rows:

In [ ]:
np.vstack((K,M))

In [ ]:
np.concatenate([K, M], axis = 0)

### Merging data sets along columns:

In [ ]:
np.hstack((K,M))

In [ ]:
np.concatenate([K, M.T], axis = 1)

### Removing Outliers

In [ ]:
arr = [10, 386, 479, 627, 20, 523, 482, 483, 542, 699, 535, 617, 577, 471, 615, 583, 441, 562, 563, 
       527, 453, 530, 433, 541, 585, 704, 443, 569, 430, 637, 331, 511, 552, 496, 484, 566, 554, 472, 
       335, 440, 579, 341, 545, 615, 548, 604, 439, 556, 442, 461, 624, 611, 444, 578, 405, 487, 490, 
       496, 398, 512, 422, 455, 449, 432, 607, 679, 434, 597, 639, 565, 415, 486, 668, 414, 665, 763, 
       557, 304, 404, 454, 689, 610, 483, 441, 657, 590, 492, 476, 437, 483, 529, 363, 711, 543]

In [ ]:
elements = np.array(arr)

In [ ]:
mean = np.mean(elements, axis=0)
sd = np.std(elements, axis=0)

### Removing Outliers

In [ ]:
final_list = [x for x in arr if (x > mean - 2 * sd)]
final_list = [x for x in final_list if (x < mean + 2 * sd)]

In [ ]:
print(final_list)