# Assignment 1

# MAS DSE200

## Instructions

* The answers to the questions should be submitted on github. 
* You don’t need to explain your approach (unless specified) so please be concise in your submission. 
* To obtain full marks for a question, both the answer and the code should be correct. 
* Completely wrong (or missing) code with correct answer will result in zero marks. 
* Please code the solution in the space provided.

# Part 1: Python

**1.1**:  Write a program to swap 2 variables and print their data types

* Initialize 2 variables my_int = 5 , and my_float = 1.5
* Swap these variables such that my_int now holds the value of my_float and vice versa
* Verify this by printing their data types 

In [67]:
# COMPLETE THIS CELL
my_int =5
my_float = 1.5
x = my_int
my_int = my_float
my_float = x

print ("Value of my_int = ", my_int)
print ("Data type of my_int = ", type(my_int) )
print ("Value of my_float = ", my_float)
print ("Data type of my_float = ", type (my_float))

Value of my_int =  1.5
Data type of my_int =  <class 'float'>
Value of my_float =  5
Data type of my_float =  <class 'int'>


**1.2**  Write a Python Program to Calculate the Area of a Triangle

* Initialize the 3 sides of the triangle a, b and c to 5, 6 and 7 
* Calculate the semiperimeter using the formula - s = (a+b+c)/2
* Calculate the area using the formula - area = √(s(s-a)*(s-b)*(s-c))

In [68]:
# COMPLETE THIS CELL
import math  

a = 5
b = 6
c = 7

s = (a + b + c)*0.5 # calculate the semi-perimeter
area = math.sqrt(s*(s-a)*(s-b)*(s-c)) # calculate the area

print('The area of the triangle is %0.2f' %area)

The area of the triangle is 14.70


**1.3**: Write a Python Program to Check if a Number is Odd or Even

* Initialize a variable that takes input from user
* Check and print if the number is odd or even

In [72]:
# COMPLETE THIS CELL

num = input('Enter number to check if it is Odd or Even: ') # Take input from user 
x = int(num) % 2
#print (x)
if x==0:
    print ('It is Even number')
else:
    print ('It is Odd number')


Enter number to check if it is Odd or Even: 115
It is Odd number


**1.4**: Write a Python Program to Check Whether a String is Palindrome or Not

* Initialize a string
* Lower case it to allow easy comparison
* Check using if-else statements if the string is a palindrome 
* A palindrome is a string which is same read forward or backwards.

In [81]:
# COMPLETE THIS CELL

def check(x):
    if x%2 ==0:
        return 'even'
    else:
        return 'odd'

#my_str = 'aIbohPhoBiA' # change this value for a different output
my_str = 'Madam'
s = my_str.lower()
x = list(s)
a = len(x)
#print(a)
l = check(a)
#print(l)
i = a//2
if l == 'even':
    xx = x[:i]
    #print(xx)
    yy = x[i:]
    #print(yy)
    yy.reverse()
    #print(yy)
    if xx == yy:
        print('It is Palindrome ')
    else:
        print('It is not Palindrome')
else:
    xx = x[:i+1]
   # print(xx)
    yy = x[i:]
    #print(yy)
    yy.reverse()
    #print(yy)
    if xx == yy:
        print('It is Palindrome ')
    else:
        print('It is not Palindrome')
    

It is Palindrome 


**1.6**  **Print numbers divisible by 3 between 1 and 20, inclusive**

* Take upper limit 20 using range
* Iterate through these numbers using for loop
* Print only a number divisible by 3 using if

In [87]:
# COMPLETE THIS CELL

limit = range(1,21)
#print(limit)
ans = [number for number in limit if number % 3 ==0] # Complete the loop
print (ans)

range(1, 21)
[3, 6, 9, 12, 15, 18]


**1.7** Write a Python Program to print the following pattern

* Initialize a variable n that denotes the number of lines
* Use nested for loops to print the following pattern 

1<br>
1 2<br>
1 2 3<br> 
1 2 3 4<br> 
1 2 3 4 5<br> 

In [92]:
# COMPLETE CELL BELOW

n = 5
for i in range(1,n+1):
    for j in range(1,i+1):
        print(j , end=" ")
    print ("\r")
        


1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


### 1.8 Write a Python Program that defines a function to Remove Punctuations From a String

* You can initialize a string of your choice 
* Define the function 
* Use a for loop to remove punctuations

In [95]:
# COMPLETE THE CELL BELOW 

punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''# define punctuation
print (type(punctuations))
my_str = "Hello!!!, he said ---and went."
#my_str = ""'fdsjfpsjfw!:,dsfljdsls.fsljfs//sdljfs?""'


#s = input("Enter any string with punctuations: ")

def removePunc(s):
    nop =""
    for c in s:
        if c not in punctuations:
            nop = nop + c
    return nop
    
    # Complete the function using a for loop
        

# my_str = input("Enter a string: ") # To take input from the user

print (removePunc(my_str))

<class 'str'>
Hello he said and went


### 1.9 **Write a program to define a function that takes a limit as a parameter and returns the sum of all numbers upto that limit (exclusive)**

* You can define a limit of your choice 
* Define the function 
* Use a for loop to add numbers upto the limit

In [96]:
# COMPLETE THE CELL BELOW 

def sum(limit): # Complete the function using a for loop and range
    x = 0
    for i in range(limit):
        x = x + i
    return x
    
limit = 10 # Define a limit of your choice 
total = sum(limit)
print ("Result is", total)


Result is 45


### 1.10 Define a class named Rectangle that can calculate the area

* The class can be constructed by a length and width
* The class has a method which can compute the area 

In [97]:
# COMPLETE CELL BELOW 

class Rectangle(object):
    def __init__(self,l,w):
        self.l = l
        self.w = w   
    def area(self):
        area = self.l * self.w
        return area

r = Rectangle(3,4) 
a = r.area()
print(a)

<class '__main__.Rectangle'>
12


# Part 2: Numpy

### Data

Download the `wine_data.csv` and `wine_modified.csv` data from tritoned and place the file in the same folder as this jupyter notebook.

In [102]:
import numpy as np

raw_data = np.genfromtxt('./wine_data.csv', delimiter=',')[1:]

In [103]:
print(raw_data)

[[1.253e+01 5.510e+00 2.640e+00 ... 1.690e+00 5.150e+02 3.000e+00]
 [1.349e+01 1.660e+00 2.240e+00 ... 2.780e+00 4.720e+02 2.000e+00]
 [1.375e+01 1.730e+00 2.410e+00 ... 2.900e+00 1.320e+03 1.000e+00]
 ...
 [1.279e+01 2.670e+00 2.480e+00 ... 1.470e+00 4.800e+02 3.000e+00]
 [1.377e+01 1.900e+00 2.680e+00 ... 2.930e+00 1.375e+03 1.000e+00]
 [1.324e+01 2.590e+00 2.870e+00 ... 2.930e+00 7.350e+02 1.000e+00]]


In [104]:
print(raw_data)
print(raw_data.shape)

[[1.253e+01 5.510e+00 2.640e+00 ... 1.690e+00 5.150e+02 3.000e+00]
 [1.349e+01 1.660e+00 2.240e+00 ... 2.780e+00 4.720e+02 2.000e+00]
 [1.375e+01 1.730e+00 2.410e+00 ... 2.900e+00 1.320e+03 1.000e+00]
 ...
 [1.279e+01 2.670e+00 2.480e+00 ... 1.470e+00 4.800e+02 3.000e+00]
 [1.377e+01 1.900e+00 2.680e+00 ... 2.930e+00 1.375e+03 1.000e+00]
 [1.324e+01 2.590e+00 2.870e+00 ... 2.930e+00 7.350e+02 1.000e+00]]
(100, 14)


**2.1**: Write code to find out how many unique classes are there in the dataset.

In [109]:
## SOLUTION 1
print(type(raw_data))
un_classes = raw_data[:, 13]
print(un_classes)
u= np.unique(un_classes)

print("There are {} unquie classes in this dataset and list it here {}".format(len(u),u))




<class 'numpy.ndarray'>
[3. 2. 1. 2. 1. 2. 3. 3. 2. 2. 1. 1. 3. 2. 2. 2. 2. 2. 1. 3. 1. 2. 2. 2.
 1. 1. 3. 1. 1. 1. 3. 1. 1. 2. 1. 3. 1. 2. 2. 3. 2. 2. 2. 2. 1. 2. 2. 2.
 2. 2. 1. 2. 3. 1. 1. 3. 3. 2. 2. 2. 2. 3. 2. 3. 3. 2. 2. 1. 3. 1. 1. 1.
 2. 2. 3. 3. 2. 2. 3. 3. 2. 1. 1. 3. 2. 1. 2. 3. 2. 2. 2. 1. 1. 3. 3. 2.
 1. 3. 1. 1.]
There are 3 unquie classes in this dataset and list it here [1 2 3]


**2.2**: Calculate the row-wise sum of the data.

In [110]:
## SOLUTION 
row_wise_sum = np.sum(raw_data,axis=1)
print("The row-wise sum of the data is lised below\n ", row_wise_sum)
print(row_wise_sum.shape)


The row-wise sum of the data is lised below
  [ 671.31      614.91     1461.        428.88     1671.6       570.3
  869.35      666.42      625.29      527.67     1142.64     1292.52
  878.19      631.12      643.34      519.77      659.51      505.84
 1702.52      720.6      1302.79      589.55      630.72      608.74
 1445.95     1437.46      611.059999 1044.5       966.36     1355.12
  827.59     1197.46     1616.23      525.59      927.08      832.4
 1248.08      597.72      700.57      809.24      524.49      656.85
  458.7       762.32     1413.44      560.86      827.85      547.32
  723.56      761.33     1139.88      413.33      601.6      1428.11
 1469.78      697.57      799.59      714.3       543.88      498.54
 1021.236    1039.27      747.92      841.02      673.33      507.9
  915.92     1677.79      921.95     1293.9      1426.28     1195.1
  516.27      637.38      830.23      656.41      706.38      453.9
  911.74      831.01      597.8       995.46     1013.93     1

**2.3**: Calculate the column-wise mean of the data.

In [107]:
## SOLUTION 3
column_wise_mean=raw_data.mean(axis=0)

print("The column-wise mean of the data is listed below:\n", column_wise_mean)
print(column_wise_mean.shape)

row_wise_mean=raw_data.mean(axis=1)
print("\n\nThe row-wise mean of the data is listed below:\n", row_wise_mean)
print(row_wise_mean.shape)

The column-wise mean of the data is listed below:
 [1.29517000e+01 2.36250000e+00 2.32670000e+00 1.93720000e+01
 9.80500000e+01 2.25280000e+00 1.98770000e+00 3.68700000e-01
 1.59900000e+00 4.99539999e+00 9.73760000e-01 2.60500000e+00
 7.17770000e+02 1.94000000e+00]
(14,)


The row-wise mean of the data is listed below:
 [ 47.95071429  43.92214286 104.35714286  30.63428571 119.4
  40.73571429  62.09642857  47.60142857  44.66357143  37.69071429
  81.61714286  92.32285714  62.72785714  45.08        45.95285714
  37.12642857  47.10785714  36.13142857 121.60857143  51.47142857
  93.05642857  42.11071429  45.05142857  43.48142857 103.28214286
 102.67571429  43.64714279  74.60714286  69.02571429  96.79428571
  59.11357143  85.53285714 115.445       37.54214286  66.22
  59.45714286  89.14857143  42.69428571  50.04071429  57.80285714
  37.46357143  46.91785714  32.76428571  54.45142857 100.96
  40.06142857  59.13214286  39.09428571  51.68285714  54.38071429
  81.42        29.52357143  42.971428

**2.4**: Calculate the class-wise mean and standard deviation of the each column.

In [112]:
## SOLUTION 4

std_column= np.std(raw_data, axis=0)
print(std_column)
print(std_column.shape)
un_classes = raw_data[:, 13]
#print(un_classes)
class_wise_mean = un_classes.mean()
print(class_wise_mean)

[8.38264940e-01 1.12796398e+00 2.83968502e-01 3.47102521e+00
 1.31539918e+01 6.10832350e-01 9.44449951e-01 1.27142872e-01
 6.05323880e-01 2.42813194e+00 2.35441760e-01 6.94683381e-01
 3.24169550e+02 7.45922248e-01]
(14,)
1.94


Use `wine_modified.csv` for the following questions.

In [116]:
raw_data1 = np.genfromtxt('./wine_modified.csv', delimiter=',')[1:]
print(raw_data1)

[[1.000e+00 1.423e+01 1.710e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.000e+00 1.320e+01 1.780e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.000e+00 1.316e+01 2.360e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [3.000e+00 1.327e+01 4.280e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [3.000e+00 1.317e+01 2.590e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [3.000e+00 1.413e+01 4.100e+00 ... 6.100e-01 1.600e+00 5.600e+02]]


**2.5** (optional): Remove the rows with missing labels (’class’) and rows with more than 7 missing features. Report the remaining number of rows.

In [131]:
## SOLUTION 5
import pandas as pd
r = raw_data1[:, 0]
print(r)
rr = r[r!= nan ]
print(rr)


SyntaxError: invalid syntax (<ipython-input-131-54fdf2bafed5>, line 5)

**2.6** (optional): Remove features with >50% of missing values. For other features with missing values fill them with the mean of the corresponding features. Report the removed features (if any) and standard deviation of features with missing values after filling.

In [ ]:
## SOLUTION 6


**2.7** (optional): Detect and remove rows with any outliers/incorrect values in features ’alcohol’ and ’proline’ (if any). Clearly state the basis of your removal in comments.

In [ ]:
## SOLUTION 7